# Generated by Django 4.1.13 on 2023-12-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_medicationreminder_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание'),
        ),
    ]
