# Generated by Django 4.1.7 on 2023-11-06 22:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('chat_id', models.CharField(max_length=20, unique=True, verbose_name='Телеграм ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{11,15}$', message='Номер телефона должен быть в формате +9989XXXXXXXX')], verbose_name='Номер телефона')),
                ('lang', models.CharField(choices=[('ru', 'Русский'), ('uz', 'Узбекский')], default='ru', max_length=2, verbose_name='Язык')),
                ('roots', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='Права')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
